import { randomUUID } from 'node:crypto';

import type {
  AgentRuntime,
  StartAgentTurnInput,
} from '../../../packages/agent-runtime/src/index';
import {
  AgentRuntimeError,
  parseTurnSteerRace,
} from '../../../packages/agent-runtime/src/index';
import {
  createThreadPendingSteerRecord,
  getThreadRecordById,
  type DatabaseClient,
  updateThreadRecord,
  upsertThreadHistoryItemRecord,
  upsertThreadTurnMetadata,
} from '../../../packages/db/src/index';
import type {
  CollaborationModeDto,
  ReasoningEffortDto,
  SandboxModeDto,
  ThreadContextUsageDto,
  ThreadDto,
} from '../../../packages/shared/src/index';
import { truncateAutoThreadTitle } from '../../../packages/shared/src/index';
import { HttpError } from './app';
import { ThreadLiveStateStore } from './thread-live-state-store';
import {
  buildThreadTurnPricingSnapshot,
  shouldResetThreadContextUsageForTurnStart,
} from './thread-usage-accounting';
import {
  ensureFastModeSupported,
  ThreadProviderRuntimeCoordinator,
} from './thread-provider-runtime-coordinator';

interface PromptTurnRecord {
  id: string;
  provider?: string | null;
  providerSessionId: string;
  title: string;
}

interface RunningPromptTurnRecord extends PromptTurnRecord {
  providerTurnId: string;
  status: string | null;
  activeTurnCollaborationMode?: string | null;
}

interface PromptTurnInput {
  prompt: string;
  displayPrompt?: string | null;
  developerInstructions?: string | null;
  effectiveModel: string | null;
  normalizedReasoning: ReasoningEffortDto | null;
  collaborationMode: CollaborationModeDto;
  sandboxMode: SandboxModeDto;
  performanceMode: 'fast' | 'standard';
  workspacePath: string;
  hidden?: boolean;
  displayTurnId?: string | null;
}

interface SteerPromptTurnInput extends PromptTurnInput {
  displayPrompt: string;
  clientRequestId: string | null;
}

interface ThreadPromptTurnCoordinatorCallbacks {
  runtimeForProvider(provider: string | null | undefined): AgentRuntime;
  resetThreadContextUsage(localThreadId: string, emitEvent: boolean): void;
  getThreadContextUsage(localThreadId: string): ThreadContextUsageDto;
  invalidateThreadDetailCache(localThreadId: string): void;
  emitThreadUpdated(localThreadId: string, payload: { reason: 'pending_steer_updated' }): void;
  toThreadDto(record: unknown, loadedIds: Set<string>): ThreadDto;
}

function isAutoGeneratedTitle(title: string | null | undefined) {
  const normalized = title?.trim();
  return !normalized || normalized === 'Untitled thread' || normalized === 'Thread';
}

function errorMessage(error: unknown) {
  return error instanceof Error ? error.message : String(error);
}

function promptStartFailureMessage(
  error: unknown,
  runtime: AgentRuntime,
  fallbackProvider: string | null | undefined,
) {
  const providerLabel = runtime.displayName || fallbackProvider || 'Agent backend';
  const rawMessage = errorMessage(error).trim() || 'Unknown error.';
  const codeLabel = error instanceof AgentRuntimeError ? ` (${error.code})` : '';
  return `${providerLabel} failed to start this turn${codeLabel}: ${rawMessage}`;
}

export class ThreadPromptTurnCoordinator {
  constructor(
    private readonly db: DatabaseClient,
    private readonly liveState: ThreadLiveStateStore,
    private readonly providerRuntime: ThreadProviderRuntimeCoordinator,
    private readonly callbacks: ThreadPromptTurnCoordinatorCallbacks,
  ) {}

  async startPromptTurn(
    localThreadId: string,
    record: PromptTurnRecord,
    input: PromptTurnInput,
  ): Promise<ThreadDto> {
    const displayPrompt = input.displayPrompt ?? input.prompt;
    const runtime = this.callbacks.runtimeForProvider(record.provider);
    const modelRecords = await runtime.listModels().catch(() => []);
    ensureFastModeSupported(
      input.effectiveModel,
      input.performanceMode === 'fast',
      modelRecords,
    );
    const pricingSnapshot = buildThreadTurnPricingSnapshot(
      input.effectiveModel,
      input.performanceMode === 'fast',
    );
    const startTurnInput: StartAgentTurnInput = {
      providerSessionId: record.providerSessionId,
      prompt: input.prompt,
      displayPrompt,
      developerInstructions: input.developerInstructions ?? null,
      model: input.effectiveModel,
      performanceMode: input.performanceMode,
      reasoningEffort: input.normalizedReasoning,
      collaborationMode: input.collaborationMode,
      sandboxMode: input.sandboxMode,
      workspacePath: input.workspacePath,
    };
    if (input.hidden !== undefined) {
      startTurnInput.hidden = input.hidden;
    }
    if (input.displayTurnId) {
      startTurnInput.displayTurnId = input.displayTurnId;
    }
    let turn: Awaited<ReturnType<AgentRuntime['startTurn']>>;
    try {
      turn = await runtime.startTurn(startTurnInput);
    } catch (error) {
      const failureMessage = promptStartFailureMessage(error, runtime, record.provider);
      this.persistPromptStartFailure(localThreadId, record, input, {
        displayPrompt,
        message: failureMessage,
        modelRecords,
        pricingSnapshot,
      });
      throw new HttpError(503, {
        code: 'service_unavailable',
        message: failureMessage,
      });
    }
    const displayTurnId = input.displayTurnId ?? turn.providerTurnId;
    if (displayTurnId !== turn.providerTurnId) {
      this.liveState.setRuntimeDisplayTurnMapping(localThreadId, {
        runtimeTurnId: turn.providerTurnId,
        displayTurnId,
      });
      if (input.hidden) {
        this.liveState.hideRuntimeTurn(localThreadId, turn.providerTurnId);
      }
    }
    upsertThreadTurnMetadata(this.db, {
      threadId: localThreadId,
      turnId: displayTurnId,
      model: input.effectiveModel,
      reasoningEffort: input.normalizedReasoning,
      reasoningEffortAvailable: this.providerRuntime.reasoningEffortAvailableForModel(
        modelRecords,
        input.effectiveModel,
      ),
      pricingModelKey: pricingSnapshot?.pricingModelKey ?? null,
      pricingTierKey: pricingSnapshot?.pricingTierKey ?? null,
      displayPrompt,
    });

    const patch: Parameters<typeof updateThreadRecord>[2] = {
      providerTurnId: turn.providerTurnId,
      status: 'running',
      summaryText: displayPrompt,
      lastError: null,
      lastTurnStartedAt: new Date().toISOString(),
      model: input.effectiveModel,
      reasoningEffort: input.normalizedReasoning,
      collaborationMode: input.collaborationMode,
      activeTurnCollaborationMode: input.collaborationMode,
      sandboxMode: input.sandboxMode,
    };

    if (isAutoGeneratedTitle(record.title)) {
      patch.title = truncateAutoThreadTitle(displayPrompt);
    }
    if (input.hidden) {
      delete patch.summaryText;
      delete patch.title;
    }

    updateThreadRecord(this.db, localThreadId, patch);
    this.liveState.setLivePlan(localThreadId, null);
    if (
      shouldResetThreadContextUsageForTurnStart(
        this.callbacks.getThreadContextUsage(localThreadId),
      )
    ) {
      this.callbacks.resetThreadContextUsage(localThreadId, true);
    }
    this.callbacks.invalidateThreadDetailCache(localThreadId);
    const updated = getThreadRecordById(this.db, localThreadId)!;

    return this.callbacks.toThreadDto(updated, new Set([record.providerSessionId]));
  }

  private persistPromptStartFailure(
    localThreadId: string,
    record: PromptTurnRecord,
    input: PromptTurnInput,
    failure: {
      displayPrompt: string;
      message: string;
      modelRecords: Awaited<ReturnType<AgentRuntime['listModels']>>;
      pricingSnapshot: ReturnType<typeof buildThreadTurnPricingSnapshot>;
    },
  ) {
    const now = new Date().toISOString();
    const displayTurnId = input.displayTurnId ?? `local-failed-${randomUUID()}`;
    const items = input.hidden
      ? [
          {
            id: `${displayTurnId}:error`,
            kind: 'agentMessage' as const,
            text: failure.message,
            status: 'failed',
            createdAt: now,
            transcriptOrder: 0,
            sourceTurnId: displayTurnId,
          },
        ]
      : [
          {
            id: `${displayTurnId}:user`,
            kind: 'userMessage' as const,
            text: failure.displayPrompt,
            createdAt: now,
            transcriptOrder: 0,
          },
          {
            id: `${displayTurnId}:error`,
            kind: 'agentMessage' as const,
            text: failure.message,
            status: 'failed',
            createdAt: now,
            transcriptOrder: 1,
            sourceTurnId: displayTurnId,
          },
        ];

    upsertThreadTurnMetadata(this.db, {
      threadId: localThreadId,
      turnId: displayTurnId,
      model: input.effectiveModel,
      reasoningEffort: input.normalizedReasoning,
      reasoningEffortAvailable: this.providerRuntime.reasoningEffortAvailableForModel(
        failure.modelRecords,
        input.effectiveModel,
      ),
      pricingModelKey: failure.pricingSnapshot?.pricingModelKey ?? null,
      pricingTierKey: failure.pricingSnapshot?.pricingTierKey ?? null,
      displayPrompt: input.hidden ? null : failure.displayPrompt,
    });

    for (const item of items) {
      upsertThreadHistoryItemRecord(this.db, {
        threadId: localThreadId,
        turnId: displayTurnId,
        itemId: item.id,
        itemJson: JSON.stringify(item),
      });
    }

    const patch: Parameters<typeof updateThreadRecord>[2] = {
      providerTurnId: displayTurnId,
      status: 'failed',
      lastError: failure.message,
      lastTurnStartedAt: now,
      lastTurnCompletedAt: now,
      model: input.effectiveModel,
      reasoningEffort: input.normalizedReasoning,
      collaborationMode: input.collaborationMode,
      sandboxMode: input.sandboxMode,
    };
    if (!input.hidden) {
      patch.summaryText = failure.displayPrompt;
      if (isAutoGeneratedTitle(record.title)) {
        patch.title = truncateAutoThreadTitle(failure.displayPrompt);
      }
    }

    updateThreadRecord(this.db, localThreadId, patch);
    this.liveState.setLivePlan(localThreadId, null);
    this.liveState.setLiveItems(localThreadId, null);
    this.callbacks.invalidateThreadDetailCache(localThreadId);
  }

  async steerOrStartPromptTurn(
    localThreadId: string,
    record: RunningPromptTurnRecord,
    input: SteerPromptTurnInput,
  ): Promise<ThreadDto> {
    const runtime = this.callbacks.runtimeForProvider(record.provider);
    let steerTurnId = record.providerTurnId;
    let retriedAfterTurnMismatch = false;

    while (steerTurnId) {
      try {
        if (!runtime.sendInput) {
          throw new HttpError(409, {
            code: 'conflict',
            message: 'This backend does not support sending input while a turn is running.',
          });
        }
        await runtime.sendInput({
          providerSessionId: record.providerSessionId,
          providerTurnId: steerTurnId,
          prompt: input.prompt,
          workspacePath: input.workspacePath,
        });

        updateThreadRecord(this.db, localThreadId, {
          providerTurnId: steerTurnId,
          status: 'running',
          lastError: null,
        });
        createThreadPendingSteerRecord(this.db, {
          threadId: localThreadId,
          turnId: steerTurnId,
          clientRequestId: input.clientRequestId,
          displayPrompt: input.displayPrompt,
          submittedPrompt: input.prompt,
          delivery: 'steer',
        });
        this.callbacks.invalidateThreadDetailCache(localThreadId);
        this.callbacks.emitThreadUpdated(localThreadId, {
          reason: 'pending_steer_updated',
        });

        const updated = getThreadRecordById(this.db, localThreadId)!;
        return this.callbacks.toThreadDto(updated, new Set([record.providerSessionId]));
      } catch (error) {
        const steerRace = parseTurnSteerRace(error);
        if (
          steerRace?.type === 'turnIdMismatch' &&
          !retriedAfterTurnMismatch &&
          steerRace.actualTurnId !== steerTurnId
        ) {
          steerTurnId = steerRace.actualTurnId;
          retriedAfterTurnMismatch = true;
          updateThreadRecord(this.db, localThreadId, {
            providerTurnId: steerTurnId,
            status: 'running',
          });
          continue;
        }

        if (!steerRace) {
          throw error;
        }

        break;
      }
    }

    return this.startPromptTurn(localThreadId, record, {
      prompt: input.displayPrompt,
      displayPrompt: input.displayPrompt,
      effectiveModel: input.effectiveModel,
      normalizedReasoning: input.normalizedReasoning,
      collaborationMode: input.collaborationMode,
      sandboxMode: input.sandboxMode,
      performanceMode: input.performanceMode,
      workspacePath: input.workspacePath,
      developerInstructions: input.developerInstructions ?? null,
    });
  }

  async queueContinuationPromptTurn(
    localThreadId: string,
    record: RunningPromptTurnRecord,
    input: SteerPromptTurnInput,
  ): Promise<ThreadDto> {
    const displayTurnId =
      this.liveState.displayTurnIdForRuntimeTurn(localThreadId, record.providerTurnId) ??
      record.providerTurnId;

    updateThreadRecord(this.db, localThreadId, {
      providerTurnId: record.providerTurnId,
      status: 'running',
      lastError: null,
    });
    createThreadPendingSteerRecord(this.db, {
      threadId: localThreadId,
      turnId: displayTurnId,
      clientRequestId: input.clientRequestId,
      displayPrompt: input.displayPrompt,
      submittedPrompt: input.prompt,
      delivery: 'continuation',
      turnConfigJson: JSON.stringify({
        effectiveModel: input.effectiveModel,
        normalizedReasoning: input.normalizedReasoning,
        collaborationMode: input.collaborationMode,
        sandboxMode: input.sandboxMode,
        performanceMode: input.performanceMode,
        startNewTurn:
          input.collaborationMode !==
          (record.activeTurnCollaborationMode === 'plan' ? 'plan' : 'default'),
      }),
    });
    this.callbacks.invalidateThreadDetailCache(localThreadId);
    this.callbacks.emitThreadUpdated(localThreadId, {
      reason: 'pending_steer_updated',
    });

    const updated = getThreadRecordById(this.db, localThreadId)!;
    return this.callbacks.toThreadDto(updated, new Set([record.providerSessionId]));
  }
}
