import {
  AgentRuntimeEvent,
} from '../../../packages/agent-runtime/src/index';
import {
  DatabaseClient,
  getThreadRecordById,
  getThreadRecordByProviderSessionId,
  markActiveThreadGoalRecordTerminated,
  updateThreadRecord,
  upsertThreadTurnMetadata,
} from '../../../packages/db/src/index';
import {
  ThreadEventPayloadMap,
  ThreadGoalDto,
  ThreadHistoryItemDto,
  truncateAutoThreadTitle,
} from '../../../packages/shared/src/index';
import { ThreadLiveStateStore } from './thread-live-state-store';
import {
  buildThreadContextUsageFromPayload,
  buildThreadTurnPricingSnapshot,
  stringifyStoredThreadTurnTokenUsageState,
  ThreadContextTokenUsagePayload,
  ThreadUsageAccounting,
} from './thread-usage-accounting';

type ThreadRecord = NonNullable<ReturnType<typeof getThreadRecordById>>;

export interface ThreadRuntimeEventProjectorCallbacks {
  appendLiveAgentMessageDelta(input: {
    localThreadId: string;
    turnId: string;
    itemId: string;
    delta: string;
    sequence: number;
  }): void;
  clearPendingPlanDecisionRequests(localThreadId: string, emitEvents: boolean): void;
  clearPendingSteersForTurn(localThreadId: string, turnId: string): void;
  clearTerminalPendingRequests(localThreadId: string, emitEvents: boolean): void;
  copyRuntimeTurnTokenUsageToDisplayTurn(
    localThreadId: string,
    runtimeTurnId: string,
    displayTurnId: string,
  ): void;
  createPendingPlanDecisionRequest(
    localThreadId: string,
    turnId: string,
    emitEvents: boolean,
  ): void;
  deletePersistedHistoryItemsForTurn(localThreadId: string, turnId: string): void;
  dismissPlanDecisionTurn(localThreadId: string): void;
  emitThreadEvent<Type extends keyof ThreadEventPayloadMap>(
    type: Type,
    threadId: string,
    payload: ThreadEventPayloadMap[Type],
  ): void;
  fastModeForProvider(provider: string | null | undefined, fastMode: unknown): boolean;
  hasPendingAskUserQuestion(localThreadId: string): boolean;
  invalidateThreadDetailCache(localThreadId: string): void;
  listThreadGoalHistory(localThreadId: string): ThreadGoalDto[];
  normalizeCollaborationMode(value: string | null | undefined): 'default' | 'plan';
  normalizeReasoningEffort(value: string | null | undefined): any;
  normalizeThreadGoalStatusForThread(goal: ThreadGoalDto, record: ThreadRecord): ThreadGoalDto;
  persistLiveHistoryItem(
    localThreadId: string,
    turnId: string,
    item: ThreadHistoryItemDto,
  ): void;
  persistFinalTurnOrderingHints(
    localThreadId: string,
    turnId: string,
    items: ThreadHistoryItemDto[],
  ): void;
  persistRuntimeTurnItemsAsDisplayTurn(
    localThreadId: string,
    runtimeTurnId: string,
    displayTurnId: string,
    items: ThreadHistoryItemDto[],
  ): void;
  persistThreadGoalSnapshot(
    localThreadId: string,
    goal: ThreadGoalDto,
  ): unknown;
  resetThreadContextUsage(localThreadId: string, emitEvent?: boolean): void;
  setThreadContextUsage(
    localThreadId: string,
    usage: ReturnType<typeof buildThreadContextUsageFromPayload>,
    emitEvent?: boolean,
  ): void;
  toThreadGoalDtoFromAgentGoal(goal: Extract<AgentRuntimeEvent, { type: 'goal.updated' }>['goal']): ThreadGoalDto;
  toThreadGoalDtoFromRecord(record: unknown): ThreadGoalDto;
}

export class ThreadRuntimeEventProjector {
  constructor(
    private readonly input: {
      db: DatabaseClient;
      liveState: ThreadLiveStateStore;
      usageAccounting: ThreadUsageAccounting;
      callbacks: ThreadRuntimeEventProjectorCallbacks;
    },
  ) {}

  async handleRuntimeEvent(event: AgentRuntimeEvent) {
    const { callbacks, db, liveState, usageAccounting } = this.input;

    switch (event.type) {
      case 'session.status.changed': {
        const record = this.findRecordByProviderSessionId(
          event.provider,
          event.providerSessionId,
        );
        if (!record) {
          return;
        }

        updateThreadRecord(db, record.id, {
          status: event.status,
        });

        callbacks.emitThreadEvent('thread.updated', record.id, {
          status: getThreadRecordById(db, record.id)?.status ?? record.status
        });
        return;
      }
      case 'session.title.updated': {
        const record = this.findRecordByProviderSessionId(
          event.provider,
          event.providerSessionId,
        );
        if (!record) {
          return;
        }

        if (this.isAutoGeneratedTitle(record.title)) {
          updateThreadRecord(db, record.id, {
            title: truncateAutoThreadTitle(event.title),
          });
        }

        callbacks.emitThreadEvent('thread.updated', record.id, {
          title: getThreadRecordById(db, record.id)?.title ?? record.title
        });
        return;
      }
      case 'goal.updated': {
        const record = this.findRecordByProviderSessionId(
          event.provider,
          event.providerSessionId,
        );
        if (!record) {
          return;
        }

        const dto = callbacks.normalizeThreadGoalStatusForThread(
          callbacks.toThreadGoalDtoFromAgentGoal(event.goal),
          record,
        );
        const persistedGoal = callbacks.toThreadGoalDtoFromRecord(
          callbacks.persistThreadGoalSnapshot(record.id, dto),
        );
        callbacks.emitThreadEvent('thread.goal.updated', record.id, {
          turnId:
            liveState.displayTurnIdForRuntimeTurn(record.id, event.providerTurnId) ??
            event.providerTurnId,
          goal: persistedGoal,
          goalHistory: callbacks.listThreadGoalHistory(record.id),
        });
        return;
      }
      case 'goal.cleared': {
        const record = this.findRecordByProviderSessionId(
          event.provider,
          event.providerSessionId,
        );
        if (!record) {
          return;
        }

        markActiveThreadGoalRecordTerminated(db, record.id);
        callbacks.emitThreadEvent('thread.goal.cleared', record.id, {
          goalHistory: callbacks.listThreadGoalHistory(record.id),
        });
        return;
      }
      case 'usage.updated': {
        const record = this.findRecordByProviderSessionId(
          event.provider,
          event.providerSessionId,
        );
        if (!record) {
          return;
        }
        const tokenUsage = this.isRecord(event.usage)
          ? (event.usage as ThreadContextTokenUsagePayload)
          : null;

        const usage = buildThreadContextUsageFromPayload(
          tokenUsage,
          record.model,
        );
        callbacks.setThreadContextUsage(record.id, usage, true);
        const displayTurnId =
          liveState.displayTurnIdForRuntimeTurn(record.id, event.providerTurnId) ??
          event.providerTurnId;
        const usageUpdate = usageAccounting.updateTurnUsage({
          localThreadId: record.id,
          turnId: displayTurnId,
          tokenUsage,
        });
        if (usageUpdate) {
          callbacks.invalidateThreadDetailCache(record.id);
          callbacks.emitThreadEvent('thread.turn.token.updated', record.id, {
            turnId: displayTurnId,
            tokenUsage: usageUpdate.tokenUsage,
            priceEstimate: usageUpdate.priceEstimate,
          });
        }
        return;
      }
      case 'turn.started': {
        const record = this.findRecordByProviderSessionId(
          event.provider,
          event.providerSessionId,
        );
        if (!record) {
          return;
        }
        const rawTurnId = event.turn.providerTurnId;
        const turnId =
          liveState.displayTurnIdForRuntimeTurn(record.id, rawTurnId) ??
          rawTurnId;

        callbacks.clearPendingPlanDecisionRequests(record.id, true);
        callbacks.dismissPlanDecisionTurn(record.id);

        updateThreadRecord(db, record.id, {
          providerTurnId: rawTurnId,
          status: 'running',
          lastError: null,
          lastTurnStartedAt: new Date().toISOString()
        });
        liveState.resetRecordedTurnItemOrder(record.id, turnId);
        for (const item of event.turn.items) {
          liveState.recordTurnItemOrder(record.id, turnId, item.id);
        }
        liveState.setLivePlan(record.id, null);
        liveState.setLiveItems(record.id, null);
        callbacks.resetThreadContextUsage(record.id, true);
        const pricingSnapshot = buildThreadTurnPricingSnapshot(
          record.model,
          callbacks.fastModeForProvider(record.provider, record.fastMode),
        );
        upsertThreadTurnMetadata(db, {
          threadId: record.id,
          turnId,
          model: record.model ?? null,
          reasoningEffort: callbacks.normalizeReasoningEffort(record.reasoningEffort),
          pricingModelKey: pricingSnapshot?.pricingModelKey ?? null,
          pricingTierKey: pricingSnapshot?.pricingTierKey ?? null,
          tokenUsageJson: stringifyStoredThreadTurnTokenUsageState({
            baselineTotal: usageAccounting.turnStartBaseline(record.id, turnId),
            usage: null,
          }),
        });
        callbacks.invalidateThreadDetailCache(record.id);

        callbacks.emitThreadEvent('thread.turn.started', record.id, {
          turnId,
        });
        return;
      }
      case 'hook.started':
      case 'hook.completed': {
        const record = this.findRecordByProviderSessionId(
          event.provider,
          event.providerSessionId,
        );
        if (!record) {
          return;
        }

        const turnId = liveState.displayTurnIdForRuntimeTurn(
          record.id,
          event.providerTurnId ?? record.providerTurnId,
        );
        if (!turnId) {
          return;
        }
        const liveItem = {
          ...event.item,
          sequence: liveState.recordTurnItemOrder(record.id, turnId, event.item.id),
        };
        callbacks.persistLiveHistoryItem(record.id, turnId, liveItem);
        liveState.upsertLiveItem(record.id, turnId, liveItem);
        callbacks.emitThreadEvent(
          event.type === 'hook.started'
            ? 'thread.item.started'
            : 'thread.item.completed',
          record.id,
          {
            turnId,
            item: liveItem,
          },
        );
        return;
      }
      case 'item.started':
      case 'item.completed': {
        const record = this.findRecordByProviderSessionId(
          event.provider,
          event.providerSessionId,
        );
        if (!record) {
          return;
        }

        const displayTurnId =
          liveState.displayTurnIdForRuntimeTurn(record.id, event.providerTurnId) ??
          event.providerTurnId;
        const sequence = liveState.recordTurnItemOrder(
          record.id,
          displayTurnId,
          event.item.id,
        );
        const orderedLiveItem = {
          ...event.item,
          sequence,
        };
        callbacks.persistLiveHistoryItem(record.id, displayTurnId, orderedLiveItem);
        liveState.upsertLiveItem(record.id, displayTurnId, orderedLiveItem);
        callbacks.emitThreadEvent(
          event.type === 'item.started'
            ? 'thread.item.started'
            : 'thread.item.completed',
          record.id,
          {
            turnId: displayTurnId,
            item: orderedLiveItem,
          },
        );
        return;
      }
      case 'plan.updated': {
        const record = this.findRecordByProviderSessionId(
          event.provider,
          event.providerSessionId,
        );
        if (!record) {
          return;
        }

        const displayTurnId =
          liveState.displayTurnIdForRuntimeTurn(record.id, event.providerTurnId) ??
          event.providerTurnId;
        liveState.setLivePlan(record.id, {
          turnId: displayTurnId,
          explanation: event.explanation,
          plan: event.plan,
          updatedAt: new Date().toISOString(),
        });

        callbacks.emitThreadEvent('thread.plan.updated', record.id, {
          turnId: displayTurnId,
          explanation: event.explanation,
          plan: event.plan,
        });
        return;
      }
      case 'output.delta': {
        const record = this.findRecordByProviderSessionId(
          event.provider,
          event.providerSessionId,
        );
        if (!record) {
          return;
        }

        const displayTurnId =
          liveState.displayTurnIdForRuntimeTurn(record.id, event.providerTurnId) ??
          event.providerTurnId;
        const sequence = liveState.recordTurnItemOrder(
          record.id,
          displayTurnId,
          event.itemId,
        );
        callbacks.appendLiveAgentMessageDelta({
          localThreadId: record.id,
          turnId: displayTurnId,
          itemId: event.itemId,
          delta: event.delta,
          sequence,
        });
        callbacks.emitThreadEvent('thread.output.delta', record.id, {
          turnId: displayTurnId,
          itemId: event.itemId,
          sequence,
          delta: event.delta,
        });
        return;
      }
      case 'turn.completed': {
        const record = this.findRecordByProviderSessionId(
          event.provider,
          event.providerSessionId,
        );
        if (!record) {
          return;
        }
        const rawTurnId = event.turn.providerTurnId;
        const turnId =
          liveState.displayTurnIdForRuntimeTurn(record.id, rawTurnId) ??
          rawTurnId;
        const turnItems = event.turn.items;

        updateThreadRecord(db, record.id, {
          providerTurnId: null,
          status:
            event.turn.status === 'failed'
              ? 'failed'
              : event.turn.status === 'interrupted'
                ? 'interrupted'
                : 'idle',
          lastError: event.turn.error?.message ?? null,
          lastTurnCompletedAt: new Date().toISOString()
        });
        callbacks.persistFinalTurnOrderingHints(record.id, turnId, turnItems);
        callbacks.persistRuntimeTurnItemsAsDisplayTurn(record.id, rawTurnId, turnId, turnItems);
        liveState.setLivePlan(record.id, null);
        liveState.setLiveItems(record.id, null);
        if (rawTurnId !== turnId) {
          callbacks.deletePersistedHistoryItemsForTurn(record.id, rawTurnId);
          liveState.resetRecordedTurnItemOrder(record.id, rawTurnId);
        }
        callbacks.copyRuntimeTurnTokenUsageToDisplayTurn(record.id, rawTurnId, turnId);
        callbacks.clearPendingSteersForTurn(record.id, turnId);
        if (rawTurnId !== turnId) {
          callbacks.clearPendingSteersForTurn(record.id, rawTurnId);
        }
        callbacks.clearTerminalPendingRequests(record.id, true);
        if (
          event.turn.status === 'completed' &&
          callbacks.normalizeCollaborationMode(record.collaborationMode) === 'plan' &&
          turnItems.some((item) => item.kind === 'plan') &&
          !callbacks.hasPendingAskUserQuestion(record.id)
        ) {
          callbacks.createPendingPlanDecisionRequest(record.id, turnId, true);
        } else {
          callbacks.dismissPlanDecisionTurn(record.id);
        }
        callbacks.invalidateThreadDetailCache(record.id);

        callbacks.emitThreadEvent(
          event.turn.status === 'failed' ? 'thread.turn.failed' : 'thread.turn.completed',
          record.id,
          {
            turnId,
            status: event.turn.status,
            error: event.turn.error?.message ?? null,
          }
        );
        liveState.clearRuntimeDisplayTurnMapping(record.id, rawTurnId);
        return;
      }
      case 'turn.failed': {
        const record = this.findRecordByProviderSessionId(
          event.provider,
          event.providerSessionId,
        );
        if (!record) {
          return;
        }

        const turnId =
          liveState.displayTurnIdForRuntimeTurn(record.id, event.providerTurnId) ??
          event.providerTurnId;
        updateThreadRecord(db, record.id, {
          status: 'failed',
          lastError: event.error,
        });
        liveState.setLivePlan(record.id, null);
        liveState.setLiveItems(record.id, null);
        callbacks.clearPendingSteersForTurn(record.id, event.providerTurnId);
        if (turnId !== event.providerTurnId) {
          callbacks.clearPendingSteersForTurn(record.id, turnId);
        }
        callbacks.clearTerminalPendingRequests(record.id, true);
        callbacks.dismissPlanDecisionTurn(record.id);
        callbacks.invalidateThreadDetailCache(record.id);

        callbacks.emitThreadEvent('thread.turn.failed', record.id, {
          turnId,
          error: event.error,
          ...(event.willRetry !== undefined ? { willRetry: event.willRetry } : {}),
        });
        liveState.clearRuntimeDisplayTurnMapping(record.id, event.providerTurnId);
        return;
      }
    }
  }

  private findRecordByProviderSessionId(
    provider: string | null | undefined,
    providerSessionId: string,
  ) {
    return getThreadRecordByProviderSessionId(
      this.input.db,
      provider ?? 'codex',
      providerSessionId,
    );
  }

  private isAutoGeneratedTitle(title: string | null | undefined) {
    const normalized = title?.trim();
    return !normalized || normalized === 'Untitled thread' || normalized === 'Thread';
  }

  private isRecord(value: unknown): value is Record<string, unknown> {
    return typeof value === 'object' && value !== null && !Array.isArray(value);
  }
}
