import type {
  AgentRuntimeStatusDto,
  ThreadDetailDto,
  ThreadDto,
} from '@remote-codex/shared';

const now = new Date('2026-07-01T12:00:00.000Z').toISOString();

const mockThread: ThreadDto = {
  id: 'ios-web-fixture-thread',
  workspaceId: 'ios-web-fixture-workspace',
  provider: 'codex',
  providerSessionId: 'fixture-session',
  source: 'supervisor',
  title: 'iOS WebView migration fixture',
  model: 'gpt-5.4',
  reasoningEffort: 'medium',
  fastMode: false,
  collaborationMode: 'default',
  approvalMode: 'guarded',
  sandboxMode: 'danger-full-access',
  status: 'idle',
  summaryText: 'Fixture thread used to prove the shared web UI can render inside iOS.',
  lastError: null,
  activeTurnId: null,
  isLoaded: true,
  isPinned: false,
  createdAt: now,
  updatedAt: now,
  lastTurnStartedAt: now,
  lastTurnCompletedAt: now,
};

export const mockThreads: ThreadDto[] = [mockThread];

export const mockDetail: ThreadDetailDto = {
  thread: mockThread,
  workspace: {
    id: 'ios-web-fixture-workspace',
    hostId: 'local',
    label: 'Remote Codex',
    absPath: '/Users/mac/dev/remoteCodex',
    isFavorite: true,
    createdAt: now,
    lastOpenedAt: now,
  },
  workspacePathStatus: 'present',
  totalTurnCount: 1,
  pendingRequests: [
    {
      id: 'ios-web-approval-request',
      kind: 'requestUserInput',
      title: 'Command approval required',
      description: 'Allow the fixture command to continue.',
      turnId: 'ios-web-fixture-turn',
      itemId: 'ios-web-fixture-agent',
      createdAt: now,
      questions: [
        {
          id: 'approval',
          header: 'Approval',
          question: 'Allow this command?',
          multiSelect: false,
          isOther: false,
          isSecret: false,
          options: [
            {
              label: 'Allow',
              description: 'Approve the command.',
            },
            {
              label: 'Deny',
              description: 'Reject the command.',
            },
          ],
        },
      ],
    },
    {
      id: 'ios-web-question-request',
      kind: 'requestUserInput',
      title: 'Mode',
      description: 'Which plan style should I use?',
      turnId: 'ios-web-fixture-turn',
      itemId: 'ios-web-fixture-agent',
      createdAt: now,
      questions: [
        {
          id: 'question-1',
          header: 'Mode',
          question: 'Which plan style should I use?',
          multiSelect: false,
          isOther: true,
          isSecret: false,
          options: [
            {
              label: 'Short',
              description: 'Keep the plan concise.',
            },
            {
              label: 'Detailed',
              description: 'Include more context.',
            },
          ],
        },
      ],
    },
    {
      id: 'ios-web-plan-request',
      kind: 'planDecision',
      title: 'Plan ready',
      description: null,
      turnId: 'ios-web-fixture-turn',
      itemId: 'ios-web-fixture-agent',
      createdAt: now,
      questions: [
        {
          id: 'plan-decision',
          header: 'Plan',
          question: 'How should Codex proceed?',
          multiSelect: false,
          isOther: false,
          isSecret: false,
          options: [
            {
              label: 'Implement (Recommended)',
              description: 'Start making the proposed changes.',
            },
            {
              label: 'Stay in plan mode',
              description: 'Keep discussing the plan.',
            },
          ],
        },
      ],
    },
  ],
  pendingSteers: [],
  turns: [
    {
      id: 'ios-web-fixture-turn',
      startedAt: now,
      status: 'completed',
      error: null,
      model: 'gpt-5.4',
      reasoningEffort: 'medium',
      reasoningEffortAvailable: true,
      tokenUsage: null,
      priceEstimate: null,
      items: [
        {
          id: 'ios-web-fixture-user',
          kind: 'userMessage',
          text: 'Render the shared thread UI inside the iOS WebView host.',
          transcriptOrder: 1,
          sourceTurnId: 'ios-web-fixture-turn',
        },
        {
          id: 'ios-web-fixture-agent',
          kind: 'agentMessage',
          text: 'The shared React thread surface is loaded from the iOS bundle. Next steps are API wiring, bridge hardening, and simulator E2E coverage.',
          transcriptOrder: 2,
          sourceTurnId: 'ios-web-fixture-turn',
        },
        {
          id: 'ios-web-fixture-plan',
          kind: 'plan',
          text: 'IOS_WEBVIEW_PLAN_MARKER\n1. Keep the native shell.\n2. Render thread detail with the shared WebView UI.',
          transcriptOrder: 3,
          sourceTurnId: 'ios-web-fixture-turn',
        },
        {
          id: 'ios-web-fixture-command',
          kind: 'commandExecution',
          text: 'pnpm --filter @remote-codex/ios-thread-web test\nIOS_WEBVIEW_COMMAND_MARKER',
          previewText: 'IOS_WEBVIEW_COMMAND_MARKER',
          detailText: 'IOS_WEBVIEW_COMMAND_DETAIL_MARKER',
          status: 'completed',
          transcriptOrder: 4,
          sourceTurnId: 'ios-web-fixture-turn',
        },
        {
          id: 'ios-web-fixture-tool',
          kind: 'toolCall',
          text: 'IOS_WEBVIEW_TOOL_MARKER: inspect thread bridge messages',
          detailText: 'IOS_WEBVIEW_TOOL_DETAIL_MARKER',
          status: 'completed',
          transcriptOrder: 5,
          sourceTurnId: 'ios-web-fixture-turn',
        },
        {
          id: 'ios-web-fixture-search',
          kind: 'webSearch',
          text: 'IOS_WEBVIEW_SEARCH_MARKER: shared thread UI adapter docs',
          previewText: 'IOS_WEBVIEW_SEARCH_MARKER',
          detailText: 'IOS_WEBVIEW_SEARCH_DETAIL_MARKER',
          status: 'completed',
          transcriptOrder: 6,
          sourceTurnId: 'ios-web-fixture-turn',
        },
        {
          id: 'ios-web-fixture-file-read',
          kind: 'fileRead',
          text: 'apps/ios/WebThread/src/mockData.ts',
          previewText: 'IOS_WEBVIEW_FILE_READ_MARKER',
          detailText: 'IOS_WEBVIEW_FILE_READ_DETAIL_MARKER',
          status: 'completed',
          transcriptOrder: 7,
          sourceTurnId: 'ios-web-fixture-turn',
        },
        {
          id: 'ios-web-fixture-file-change',
          kind: 'fileChange',
          text: 'apps/ios/WebThread/src/mockData.ts',
          previewText: 'IOS_WEBVIEW_FILE_CHANGE_MARKER',
          detailText: 'IOS_WEBVIEW_FILE_CHANGE_DETAIL_MARKER',
          status: 'completed',
          changedFiles: 1,
          addedLines: 8,
          removedLines: 0,
          transcriptOrder: 8,
          sourceTurnId: 'ios-web-fixture-turn',
        },
        {
          id: 'ios-web-fixture-context',
          kind: 'contextCompaction',
          text: 'Context compacted',
          detailText: 'IOS_WEBVIEW_CONTEXT_MARKER',
          status: 'completed',
          transcriptOrder: 9,
          sourceTurnId: 'ios-web-fixture-turn',
        },
      ],
    },
  ],
  liveItems: null,
  livePlan: null,
};

export const mockStatus: AgentRuntimeStatusDto = {
  state: 'ready',
  transport: 'sdk',
  lastStartedAt: now,
  lastError: null,
  restartCount: 0,
};
