import { test, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import path from 'node:path';
import { randomUUID } from 'node:crypto';

test('missing ACP adapter asks for confirmation before installation and continues creation', async ({ page, request }) => {
  const base = `http://127.0.0.1:${process.env.E2E_API_PORT ?? 8787}`;
  const absPath = path.resolve(process.env.E2E_WORKSPACE_ROOT!, randomUUID());
  await mkdir(absPath, { recursive: true });
  const workspace = await (await request.post(`${base}/api/workspaces`, { data: { absPath, label: 'Adapter confirmation' } })).json();
  const thread = await (await request.post(`${base}/api/threads/start`, { data: { workspaceId: workspace.id, title: 'Adapter confirmation', provider: 'codex', model: 'ios-e2e-stream', approvalMode: 'yolo' } })).json();
  let installed = false;
  let installs = 0;
  let modelLoads = 0;
  let created: Record<string, unknown> | null = null;
  await page.route('**/api/agent-runtimes', route => route.fulfill({ json: [{ provider: 'acp', displayName: 'ACP', enabled: true, capabilities: { sessions: { resume: true }, turns: { start: true } }, installation: { installed: true }, status: {} }] }));
  await page.route('**/api/agent-runtimes/acp/agents', route => route.fulfill({ json: [{ id: 'codex', model: 'codex', displayName: 'OpenAI Codex', isDefault: true, selectionKind: 'agent', acpAgent: { availability: installed ? 'ready' : 'adapter_missing', serverCommand: 'codex-acp', installCommand: 'npm install fixture' } }] }));
  await page.route('**/api/agent-runtimes/acp/models*', route => { modelLoads++; return route.fulfill({ json: [{ id: 'model-a', model: 'model-a', displayName: 'Model A', isDefault: true, supportedReasoningEfforts: [], defaultReasoningEffort: null }] }); });
  await page.route('**/api/agent-runtimes/acp/install*', route => { installs++; installed = true; return route.fulfill({ json: {} }); });
  await page.route('**/api/threads/start', route => { created = route.request().postDataJSON(); return route.fulfill({ json: thread }); });
  await page.goto(`/threads/new?workspaceId=${workspace.id}`);
  await page.getByLabel('Title', { exact: true }).fill('Keep my title');
  const create = page.getByRole('button', { name: /^Create thread$/i });
  await expect(create).toBeEnabled();
  expect(installs).toBe(0);
  expect(modelLoads).toBe(0);
  await create.click();
  const prompt = page.getByRole('dialog');
  await expect(prompt).toContainText('OpenAI Codex is installed');
  await prompt.getByRole('button', { name: 'Cancel', exact: true }).click();
  expect(installs).toBe(0);
  expect(created).toBeNull();
  await create.click();
  await prompt.getByRole('button', { name: 'Install adapter', exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`/threads/${thread.id ?? thread.thread.id}$`));
  expect(installs).toBe(1);
  expect(modelLoads).toBeGreaterThan(0);
  expect(created).toMatchObject({ workspaceId: workspace.id, title: 'Keep my title', agentId: 'codex', model: 'model-a', approvalMode: 'yolo' });
});
