import { ArrowLeft, CheckCircle2, Copy, KeyRound, MonitorSmartphone, Play, RadioTower, Share2 } from 'lucide-react';
import { useEffect, type ReactNode } from 'react';
import { Link } from 'react-router-dom';

import { enableRelayMode } from '../lib/api';

const setupCommand = [
  'REMOTE_CODEX_RELAY_SERVER_URL=wss://remote-codex.example.com \\',
  'REMOTE_CODEX_RELAY_AGENT_TOKEN=rcd_... \\',
  'REMOTE_CODEX_RELAY_SUPERVISOR_PORT=45679 \\',
  'remote-codex relay-supervisor',
].join('\n');

export function RelayGuidePage() {
  useEffect(() => {
    enableRelayMode();
  }, []);

  return (
    <main className="min-h-screen bg-[var(--app-bg)] px-4 py-6 text-[var(--app-fg)] sm:px-6">
      <article className="mx-auto w-full max-w-5xl space-y-6">
        <header className="border-b border-[var(--theme-border)] pb-5">
          <Link className="relay-button-secondary mb-5 inline-flex items-center gap-2" to="/">
            <ArrowLeft className="h-4 w-4" />
            Back
          </Link>
          <p className="text-xs font-semibold uppercase tracking-[0.22em] text-[var(--theme-fg-muted)]">
            Setup guide
          </p>
          <h1 className="mt-2 text-3xl font-semibold tracking-normal text-[var(--theme-fg)]">
            Remote Codex connection modes and relay setup
          </h1>
          <p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--theme-fg-soft)]">
            Choose the connection mode first, then follow the relay flow when you need public web or mobile access to a
            private supervisor machine.
          </p>
        </header>

        <section className="grid gap-3 md:grid-cols-3">
          <ModeCard title="Local mode" detail="Use this on the same machine, emulator, LAN, or Tailscale network. It is simplest and has no relay account." />
          <ModeCard title="Server mode" detail="Use this when you directly expose a supervisor with its own server login. Good for a trusted private server." />
          <ModeCard title="Relay mode" detail="Use this when the backend machine should not accept inbound connections. The supervisor connects out to the relay." />
        </section>

        <section className="rounded-lg border border-[var(--theme-border)] bg-[var(--theme-panel)] p-4">
          <h2 className="text-lg font-semibold text-[var(--theme-fg)]">Relay setup flow</h2>
          <div className="mt-4 grid gap-3">
            <GuideStep icon={<KeyRound className="h-4 w-4" />} title="1. Register or sign in" detail="Open the relay home page, click Sign in, then create or enter your relay account." />
            <GuideStep icon={<MonitorSmartphone className="h-4 w-4" />} title="2. Create a device" detail="Go to Devices, choose a readable device name, and create a one-time token for that private supervisor." />
            <GuideStep icon={<Copy className="h-4 w-4" />} title="3. Copy the setup command" detail="Use Copy setup. The command includes the relay URL, device token, and a less common supervisor port." />
            <GuideStep icon={<Play className="h-4 w-4" />} title="4. Start supervisor on the private machine" detail="Run the copied command in the workspace host terminal. If tmux is installed, remote-codex keeps it detached by default." />
            <GuideStep icon={<RadioTower className="h-4 w-4" />} title="5. Connect and work" detail="Return to Devices, wait for Online, then Connect. Workspaces and threads are scoped through that selected device." />
            <GuideStep icon={<Share2 className="h-4 w-4" />} title="6. Share a thread when needed" detail="Inside a thread, open the export/share panel, enter another relay username, and choose thread plus workspace permissions." />
          </div>
        </section>

        <section className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(18rem,0.8fr)]">
          <div className="rounded-lg border border-[var(--theme-border)] bg-[var(--theme-panel)] p-4">
            <h2 className="text-lg font-semibold text-[var(--theme-fg)]">Example supervisor command</h2>
            <p className="mt-1 text-sm text-[var(--theme-fg-muted)]">
              The real command is generated by the relay portal. Keep the token private.
            </p>
            <pre className="mt-4 overflow-x-auto rounded-lg border border-[var(--theme-border)] bg-[var(--theme-surface-strong)] p-3 text-xs leading-5 text-[var(--theme-fg)]">
              <code>{setupCommand}</code>
            </pre>
          </div>
          <div className="rounded-lg border border-[var(--theme-border)] bg-[var(--theme-panel)] p-4">
            <h2 className="text-lg font-semibold text-[var(--theme-fg)]">After setup</h2>
            <ul className="mt-3 space-y-3 text-sm leading-6 text-[var(--theme-fg-muted)]">
              <li className="flex gap-2"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-[var(--theme-accent-strong)]" />Use Devices to switch backend machines.</li>
              <li className="flex gap-2"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-[var(--theme-accent-strong)]" />Use Shared with me to open sessions others shared.</li>
              <li className="flex gap-2"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-[var(--theme-accent-strong)]" />Use Shared by me to review access history, edit permissions, or revoke access.</li>
            </ul>
          </div>
        </section>
      </article>
    </main>
  );
}

function ModeCard({ detail, title }: { detail: string; title: string }) {
  return (
    <article className="rounded-lg border border-[var(--theme-border)] bg-[var(--theme-panel)] p-4">
      <h2 className="text-base font-semibold text-[var(--theme-fg)]">{title}</h2>
      <p className="mt-2 text-sm leading-6 text-[var(--theme-fg-muted)]">{detail}</p>
    </article>
  );
}

function GuideStep({
  detail,
  icon,
  title,
}: {
  detail: string;
  icon: ReactNode;
  title: string;
}) {
  return (
    <div className="grid gap-3 rounded-lg border border-[var(--theme-border)] bg-[var(--theme-surface)] p-3 sm:grid-cols-[2rem_minmax(0,1fr)]">
      <span className="inline-flex h-8 w-8 items-center justify-center rounded-lg border border-[var(--theme-border)] bg-[var(--theme-panel)] text-[var(--theme-accent-strong)]">
        {icon}
      </span>
      <div>
        <h3 className="text-sm font-semibold text-[var(--theme-fg)]">{title}</h3>
        <p className="mt-1 text-sm leading-6 text-[var(--theme-fg-muted)]">{detail}</p>
      </div>
    </div>
  );
}
