CREATE TABLE `threads_new` (
  `id` text PRIMARY KEY NOT NULL,
  `workspace_id` text NOT NULL,
  `provider` text DEFAULT 'codex' NOT NULL,
  `provider_session_id` text,
  `provider_turn_id` text,
  `source` text DEFAULT 'supervisor' NOT NULL,
  `title` text NOT NULL,
  `model` text,
  `reasoning_effort` text,
  `fast_mode` integer DEFAULT false NOT NULL,
  `fast_base_model` text,
  `fast_base_reasoning_effort` text,
  `collaboration_mode` text DEFAULT 'default' NOT NULL,
  `approval_mode` text,
  `sandbox_mode` text,
  `status` text,
  `summary_text` text,
  `last_error` text,
  `created_at` text NOT NULL,
  `updated_at` text NOT NULL,
  `last_turn_started_at` text,
  `last_turn_completed_at` text,
  `last_viewed_at` text,
  `is_pinned` integer DEFAULT false NOT NULL,
  `is_connected` integer DEFAULT true NOT NULL
);

INSERT INTO `threads_new` (
  `id`,
  `workspace_id`,
  `provider`,
  `provider_session_id`,
  `provider_turn_id`,
  `source`,
  `title`,
  `model`,
  `reasoning_effort`,
  `fast_mode`,
  `fast_base_model`,
  `fast_base_reasoning_effort`,
  `collaboration_mode`,
  `approval_mode`,
  `sandbox_mode`,
  `status`,
  `summary_text`,
  `last_error`,
  `created_at`,
  `updated_at`,
  `last_turn_started_at`,
  `last_turn_completed_at`,
  `last_viewed_at`,
  `is_pinned`,
  `is_connected`
)
SELECT
  `id`,
  `workspace_id`,
  COALESCE(`provider`, 'codex'),
  COALESCE(`provider_session_id`, `codex_thread_id`),
  COALESCE(`provider_turn_id`, `codex_turn_id`),
  `source`,
  `title`,
  `model`,
  `reasoning_effort`,
  `fast_mode`,
  `fast_base_model`,
  `fast_base_reasoning_effort`,
  `collaboration_mode`,
  `approval_mode`,
  `sandbox_mode`,
  `status`,
  `summary_text`,
  `last_error`,
  `created_at`,
  `updated_at`,
  `last_turn_started_at`,
  `last_turn_completed_at`,
  `last_viewed_at`,
  `is_pinned`,
  `is_connected`
FROM `threads`;

DROP TABLE `threads`;
ALTER TABLE `threads_new` RENAME TO `threads`;
