// Provider presets adapted from CC Switch src/config/*ProviderPresets.ts.
// Copyright (c) 2025 Jason Young. MIT; see THIRD_PARTY_NOTICES.md.
// Direct API presets only; OAuth, format-converting proxy and variable URLs require other services.
export const upstreamPresets = [
  {
    harness: 'claude',
    name: 'Claude Official',
    baseUrl: 'https://api.anthropic.com',
    model: '',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'Kimi',
    baseUrl: 'https://api.moonshot.cn/anthropic',
    model: 'kimi-k2.7-code',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'kimi-k2.7-code',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'kimi-k2.7-code',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'kimi-k2.7-code',
      },
    },
  },
  {
    harness: 'claude',
    name: 'Kimi Global',
    baseUrl: 'https://api.moonshot.ai/anthropic',
    model: 'kimi-k2.7-code',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'kimi-k2.7-code',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'kimi-k2.7-code',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'kimi-k2.7-code',
      },
    },
  },
  {
    harness: 'claude',
    name: 'Kimi For Coding',
    baseUrl: 'https://api.kimi.com/coding/',
    model: 'kimi-for-coding',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'kimi-for-coding',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'kimi-for-coding',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'kimi-for-coding',
        CLAUDE_CODE_MAX_CONTEXT_TOKENS: '262144',
        CLAUDE_CODE_AUTO_COMPACT_WINDOW: '262144',
      },
    },
  },
  {
    harness: 'claude',
    name: 'Kimi For Coding Global',
    baseUrl: 'https://api.kimi.ai/coding/',
    model: 'kimi-for-coding',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'kimi-for-coding',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'kimi-for-coding',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'kimi-for-coding',
        CLAUDE_CODE_MAX_CONTEXT_TOKENS: '262144',
        CLAUDE_CODE_AUTO_COMPACT_WINDOW: '262144',
      },
    },
  },
  {
    harness: 'claude',
    name: 'PackyCode',
    baseUrl: 'https://www.packyapi.ai',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'ZetaAPI',
    baseUrl: 'https://api.zetaapi.ai',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'APINebula',
    baseUrl: 'https://apinebula.ai',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'AICodeMirror',
    baseUrl: 'https://api.aicodemirror.ai/api/claudecode',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'PatewayAI',
    baseUrl: 'https://api.pateway.ai',
    model: '',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'FennoAI',
    baseUrl: 'https://api.fenno.ai',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'RunAPI',
    baseUrl: 'https://runapi.host',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'Shengsuanyun',
    baseUrl: 'https://router.shengsuanyun.com/api',
    model: 'anthropic/claude-sonnet-5',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'anthropic/claude-haiku-4.5',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'anthropic/claude-sonnet-5',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'anthropic/claude-opus-5',
      },
    },
  },
  {
    harness: 'claude',
    name: 'AIGoCode',
    baseUrl: 'https://api.aigocode.app',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'Qiniu',
    baseUrl: 'https://api.qnaigc.com',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'AICoding',
    baseUrl: 'https://api.aicoding.inc',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'SubRouter',
    baseUrl: 'https://subrouter.ai',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'FluxA Token Plan',
    baseUrl: 'https://api.baiduqianfan.ai/anthropic/tokenplan/team',
    model: 'deepseek-v4-pro',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'deepseek-v4-pro',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'deepseek-v4-pro',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'deepseek-v4-pro',
      },
    },
  },
  {
    harness: 'claude',
    name: '88API',
    baseUrl: 'https://api.88api.ai',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'APIKEY.FUN',
    baseUrl: 'https://api.apikey.fan',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: '9527CODE',
    baseUrl: 'https://9527.codes',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'ClaudeAPI',
    baseUrl: 'https://gw.apito.ai',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'Code0',
    baseUrl: 'https://code0.ai',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'TeamoRouter',
    baseUrl: 'https://api.teamorouter.cn',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'PPIO',
    baseUrl: 'https://api.ppio.com/anthropic',
    model: 'deepseek/deepseek-v4-flash-0731',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'deepseek/deepseek-v4-flash-0731',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'deepseek/deepseek-v4-flash-0731',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'deepseek/deepseek-v4-flash-0731',
      },
    },
  },
  {
    harness: 'claude',
    name: 'ClaudeCN',
    baseUrl: 'https://claudecn.top',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: '火山 Agent Plan',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/plan',
    model: 'ark-code-latest',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'ark-code-latest',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'ark-code-latest',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'ark-code-latest',
      },
    },
  },
  {
    harness: 'claude',
    name: '火山 Coding Plan',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/coding',
    model: 'ark-code-latest',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'ark-code-latest',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'ark-code-latest',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'ark-code-latest',
      },
    },
  },
  {
    harness: 'claude',
    name: 'BytePlus',
    baseUrl: 'https://ark.ap-southeast.bytepluses.com/api/coding',
    model: 'ark-code-latest',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'ark-code-latest',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'ark-code-latest',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'ark-code-latest',
      },
    },
  },
  {
    harness: 'claude',
    name: 'Volcengine Doubao',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/compatible',
    model: 'doubao-seed-2-1-pro-260628',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'doubao-seed-2-1-pro-260628',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'doubao-seed-2-1-pro-260628',
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'doubao-seed-2-1-pro-260628',
      },
    },
  },
  {
    harness: 'claude',
    name: 'SiliconFlow',
    baseUrl: 'https://api.siliconflow.cn',
    model: 'Pro/MiniMaxAI/MiniMax-M2.5',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'Pro/MiniMaxAI/MiniMax-M2.5',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'Pro/MiniMaxAI/MiniMax-M2.5',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'Pro/MiniMaxAI/MiniMax-M2.5',
      },
    },
  },
  {
    harness: 'claude',
    name: 'SiliconFlow en',
    baseUrl: 'https://api.siliconflow.com',
    model: 'MiniMaxAI/MiniMax-M3',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'MiniMaxAI/MiniMax-M3',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'MiniMaxAI/MiniMax-M3',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'MiniMaxAI/MiniMax-M3',
      },
    },
  },
  {
    harness: 'claude',
    name: 'A6API',
    baseUrl: 'https://api.a6api.com',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'Compshare',
    baseUrl: 'https://api.modelverse.cn',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'Compshare Coding Plan',
    baseUrl: 'https://cp.compshare.cn',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'CCSub',
    baseUrl: 'https://www.ccsub.net',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'SSSAiCode',
    baseUrl: 'https://node-hk.sssaicodeapi.com/api',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'SoleAPI',
    baseUrl: 'https://soleapi.com',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'Micu',
    baseUrl: 'https://www.micuapi.ai',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'RightCode',
    baseUrl: 'https://www.rightapi.ai/claude',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'Cubence',
    baseUrl: 'https://api.cubence.com',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'CrazyRouter',
    baseUrl: 'https://cn.crazyrouter.com',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'DMXAPI',
    baseUrl: 'https://www.dmxapi.cn',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'SudoCode.chat',
    baseUrl: 'https://api.sudocode.chat',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'SudoCode.us',
    baseUrl: 'https://sudocode.us',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'XycAi',
    baseUrl: 'https://apicdn.xycai.us',
    model: '',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'Tu-zi',
    baseUrl: 'https://api.tu-zi.com',
    model: '',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'Amux',
    baseUrl: 'https://api.amux.ai',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'AtlasCloud',
    baseUrl: 'https://api.atlascloud.ai',
    model: 'zai-org/glm-5.1',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'zai-org/glm-5.1',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'zai-org/glm-5.1',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'zai-org/glm-5.1',
        CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS: '1',
      },
    },
  },
  {
    harness: 'claude',
    name: 'Soshow',
    baseUrl: 'https://maas.so-show.com',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'claude-sonnet-5',
        CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS: '1',
      },
    },
  },
  {
    harness: 'claude',
    name: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com/anthropic',
    model: 'deepseek-v4-pro',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'deepseek-flash',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'deepseek-v4-pro',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'deepseek-v4-pro',
      },
    },
  },
  {
    harness: 'claude',
    name: 'OpenCode Go',
    baseUrl: 'https://opencode.ai/zen/go',
    model: 'deepseek-v4-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'deepseek-v4-flash',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'deepseek-v4-flash',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'deepseek-v4-flash',
      },
    },
  },
  {
    harness: 'claude',
    name: 'OpenCode Zen',
    baseUrl: 'https://opencode.ai/zen',
    model: 'claude-sonnet-5-5',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'claude-haiku-4-5',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'claude-sonnet-5-5',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'claude-opus-5-5',
      },
    },
  },
  {
    harness: 'claude',
    name: 'Tencent Token Plan',
    baseUrl: 'https://api.lkeap.cloud.tencent.com/plan/anthropic',
    model: 'tc-code-latest',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'tc-code-latest',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'tc-code-latest',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'tc-code-latest',
      },
    },
  },
  {
    harness: 'claude',
    name: 'Tencent Token Plan (Intl)',
    baseUrl: 'https://tokenhub-intl.tencentcloudmaas.com/plan/anthropic',
    model: 'auto',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'auto',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'auto',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'auto',
      },
    },
  },
  {
    harness: 'claude',
    name: 'Tencent Token Plan Enterprise Pro',
    baseUrl: 'https://tokenhub.tencentmaas.com/plan/anthropic',
    model: 'auto',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'auto',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'auto',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'auto',
      },
    },
  },
  {
    harness: 'claude',
    name: 'Tencent Token Plan Enterprise Pro (Intl)',
    baseUrl: 'https://tokenhub-intl.tencentcloudmaas.com/plan/anthropic',
    model: 'auto',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'auto',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'auto',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'auto',
      },
    },
  },
  {
    harness: 'claude',
    name: 'Tencent Token Plan Enterprise Lite',
    baseUrl: 'https://tokenhub.tencentmaas.com/plan/anthropic',
    model: 'auto',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'auto',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'auto',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'auto',
      },
    },
  },
  {
    harness: 'claude',
    name: 'Tencent Token Plan Enterprise Lite (Intl)',
    baseUrl: 'https://tokenhub-intl.tencentcloudmaas.com/plan/anthropic',
    model: 'auto',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'auto',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'auto',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'auto',
      },
    },
  },
  {
    harness: 'claude',
    name: 'Zhipu GLM',
    baseUrl: 'https://open.bigmodel.cn/api/anthropic',
    model: 'glm-5.3',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'glm-5.3',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'glm-5.3',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'glm-5.3',
      },
    },
  },
  {
    harness: 'claude',
    name: 'Zhipu GLM en',
    baseUrl: 'https://api.z.ai/api/anthropic',
    model: 'glm-5.3',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'glm-5.3',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'glm-5.3',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'glm-5.3',
      },
    },
  },
  {
    harness: 'claude',
    name: 'Baidu Qianfan Coding Plan',
    baseUrl: 'https://qianfan.baidubce.com/anthropic/coding',
    model: 'qianfan-code-latest',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'qianfan-code-latest',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'qianfan-code-latest',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'qianfan-code-latest',
      },
    },
  },
  {
    harness: 'claude',
    name: 'Baidu Qianfan Token Plan',
    baseUrl: 'https://qianfan.baidubce.com/anthropic/tokenplan/personal',
    model: 'deepseek-v4-pro',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'deepseek-v4-pro',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'deepseek-v4-pro',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'deepseek-v4-pro',
      },
    },
  },
  {
    harness: 'claude',
    name: '千问AI平台',
    baseUrl: 'https://dashscope.aliyuncs.com/apps/anthropic',
    model: 'qwen3.8-max',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'qwen3.8-flash',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'qwen3.7-plus',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'qwen3.8-max',
        CLAUDE_CODE_MAX_CONTEXT_TOKENS: '983616',
      },
    },
  },
  {
    harness: 'claude',
    name: '千问AI平台 Coding Plan',
    baseUrl: 'https://coding.dashscope.aliyuncs.com/apps/anthropic',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: '千问AI平台 Token Plan',
    baseUrl: 'https://token-plan.cn-beijing.maas.aliyuncs.com/apps/anthropic',
    model: 'qwen3.8-max',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'qwen3.8-flash',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'qwen3.7-plus',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'qwen3.8-max',
        CLAUDE_CODE_MAX_CONTEXT_TOKENS: '983616',
      },
    },
  },
  {
    harness: 'claude',
    name: 'QwenCloud',
    baseUrl: 'https://dashscope-intl.aliyuncs.com/apps/anthropic',
    model: 'qwen3.8-max',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'qwen3.8-flash',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'qwen3.7-plus',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'qwen3.8-max',
      },
    },
  },
  {
    harness: 'claude',
    name: 'QwenCloud For Coding',
    baseUrl: 'https://coding-intl.dashscope.aliyuncs.com/apps/anthropic',
    model: 'qwen3.7-plus',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'qwen3.7-plus',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'qwen3.7-plus',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'qwen3.7-plus',
      },
    },
  },
  {
    harness: 'claude',
    name: 'QwenCloud Token Plan',
    baseUrl:
      'https://token-plan.ap-southeast-1.maas.aliyuncs.com/apps/anthropic',
    model: 'qwen3.8-max',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'qwen3.8-flash',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'qwen3.7-plus',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'qwen3.8-max',
        CLAUDE_CODE_MAX_CONTEXT_TOKENS: '983616',
      },
    },
  },
  {
    harness: 'claude',
    name: 'StepFun',
    baseUrl: 'https://api.stepfun.com/step_plan',
    model: 'step-3.5-flash-2603',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'step-3.5-flash-2603',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'step-3.5-flash-2603',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'step-3.5-flash-2603',
      },
    },
  },
  {
    harness: 'claude',
    name: 'StepFun en',
    baseUrl: 'https://api.stepfun.ai/step_plan',
    model: 'step-3.5-flash-2603',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'step-3.5-flash-2603',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'step-3.5-flash-2603',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'step-3.5-flash-2603',
      },
    },
  },
  {
    harness: 'claude',
    name: 'ModelScope',
    baseUrl: 'https://api-inference.modelscope.cn',
    model: 'ZhipuAI/GLM-5.2',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'ZhipuAI/GLM-5.2',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'ZhipuAI/GLM-5.2',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'ZhipuAI/GLM-5.2',
      },
    },
  },
  {
    harness: 'claude',
    name: 'Longcat',
    baseUrl: 'https://api.longcat.chat/anthropic',
    model: 'LongCat-2.0',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_SMALL_FAST_MODEL: 'LongCat-2.0',
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'LongCat-2.0',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'LongCat-2.0',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'LongCat-2.0',
        CLAUDE_CODE_MAX_OUTPUT_TOKENS: '131072',
      },
    },
  },
  {
    harness: 'claude',
    name: 'MiniMax',
    baseUrl: 'https://api.minimax.cn/anthropic',
    model: 'MiniMax-M3[1M]',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        CLAUDE_CODE_AUTO_COMPACT_WINDOW: '1000000',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'MiniMax-M3[1M]',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'MiniMax-M3[1M]',
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'MiniMax-M3[1M]',
      },
    },
  },
  {
    harness: 'claude',
    name: 'MiniMax en',
    baseUrl: 'https://api.minimax.io/anthropic',
    model: 'MiniMax-M3[1M]',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        CLAUDE_CODE_AUTO_COMPACT_WINDOW: '1000000',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'MiniMax-M3[1M]',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'MiniMax-M3[1M]',
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'MiniMax-M3[1M]',
      },
    },
  },
  {
    harness: 'claude',
    name: 'BaiLing',
    baseUrl: 'https://api.ant-ling.com/anthropic',
    model: 'Ling-2.6-1T',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'Ling-2.6-1T',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'Ling-2.6-1T',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'Ling-2.6-1T',
      },
    },
  },
  {
    harness: 'claude',
    name: 'AiHubMix',
    baseUrl: 'https://aihubmix.com',
    model: '',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'CherryIN',
    baseUrl: 'https://open.cherryin.net',
    model: 'anthropic/claude-sonnet-5',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'anthropic/claude-haiku-4.5',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'anthropic/claude-sonnet-5',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'anthropic/claude-opus-5',
      },
    },
  },
  {
    harness: 'claude',
    name: 'RelaxyCode',
    baseUrl: 'https://www.relaxycode.com',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: 'E-FlowCode',
    baseUrl: 'https://e-flowcode.cc',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ENABLE_TOOL_SEARCH: 'true',
      },
    },
  },
  {
    harness: 'claude',
    name: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api',
    model: 'anthropic/claude-sonnet-5',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'anthropic/claude-haiku-4.5',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'anthropic/claude-sonnet-5',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'anthropic/claude-opus-5',
      },
    },
  },
  {
    harness: 'claude',
    name: 'TheRouter',
    baseUrl: 'https://api.therouter.ai',
    model: 'anthropic/claude-sonnet-5',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'anthropic/claude-haiku-4.5',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'anthropic/claude-sonnet-5',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'anthropic/claude-opus-5',
      },
    },
  },
  {
    harness: 'claude',
    name: 'Novita AI',
    baseUrl: 'https://api.novita.ai/anthropic',
    model: 'zai-org/glm-5.1',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'zai-org/glm-5.1',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'zai-org/glm-5.1',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'zai-org/glm-5.1',
      },
    },
  },
  {
    harness: 'claude',
    name: 'PIPELLM',
    baseUrl: 'https://cc-api.pipellm.ai',
    model: 'claude-opus-5',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'claude-haiku-4-5-20251001',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'claude-sonnet-5',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'claude-opus-5',
      },
    },
  },
  {
    harness: 'claude',
    name: 'Xiaomi MiMo',
    baseUrl: 'https://api.xiaomimimo.com/anthropic',
    model: 'mimo-v2.6-pro',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'mimo-v2.6-pro',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'mimo-v2.6-pro',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'mimo-v2.6-pro',
      },
    },
  },
  {
    harness: 'claude',
    name: 'Xiaomi MiMo Token Plan (China)',
    baseUrl: 'https://token-plan-cn.xiaomimimo.com/anthropic',
    model: 'mimo-v2.6-pro',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'mimo-v2.6-pro',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'mimo-v2.6-pro',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'mimo-v2.6-pro',
      },
    },
  },
  {
    harness: 'claude',
    name: 'JieKou AI',
    baseUrl: 'https://api.jiekou.ai/anthropic',
    model: 'claude-fable-5',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'claude-fable-5',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'claude-fable-5',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'claude-fable-5',
      },
    },
  },
  {
    harness: 'claude',
    name: 'AICodeWith',
    baseUrl: 'https://api.aicodewith.ai',
    model: '',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'claude',
    name: '模力方舟',
    baseUrl: 'https://moark.com/anthropic',
    model: 'deepseek-v4-flash-0731',
    authType: 'bearer',
    apiType: 'responses',
    settingsConfig: {
      env: {
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'deepseek-v4-flash-0731',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'deepseek-v4-flash-0731',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'deepseek-v4-flash-0731',
      },
    },
  },
  {
    harness: 'codex',
    name: 'OpenAI Official',
    baseUrl: 'https://api.openai.com/v1',
    model: '',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Kimi',
    baseUrl: 'https://api.moonshot.cn/v1',
    model: 'kimi-k3',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Kimi Global',
    baseUrl: 'https://api.moonshot.ai/v1',
    model: 'kimi-k3',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Kimi For Coding',
    baseUrl: 'https://api.kimi.com/coding/v1',
    model: 'kimi-for-coding',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Kimi For Coding Global',
    baseUrl: 'https://api.kimi.ai/coding/v1',
    model: 'kimi-for-coding',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'PackyCode',
    baseUrl: 'https://www.packyapi.ai/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'ZetaAPI',
    baseUrl: 'https://api.zetaapi.ai/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'APINebula',
    baseUrl: 'https://apinebula.ai/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      review_model: 'gpt-5.6-sol',
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'AICodeMirror',
    baseUrl: 'https://api.aicodemirror.ai/api/codex/backend-api/codex',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'PatewayAI',
    baseUrl: 'https://api.pateway.ai/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'FennoAI',
    baseUrl: 'https://api.fenno.ai',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'RunAPI',
    baseUrl: 'https://runapi.host/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Shengsuanyun',
    baseUrl: 'https://router.shengsuanyun.com/api/v1',
    model: 'openai/gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'AIGoCode',
    baseUrl: 'https://api.aigocode.app',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Qiniu',
    baseUrl: 'https://api.qnaigc.com/bypass/openai/v1',
    model: 'gpt-6-astra',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'AICoding',
    baseUrl: 'https://api.aicoding.inc',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'SubRouter',
    baseUrl: 'https://subrouter.ai/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: '88API',
    baseUrl: 'https://api.88api.ai/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'APIKEY.FUN',
    baseUrl: 'https://api.apikey.fan/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      review_model: 'gpt-5.6-sol',
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: '9527CODE',
    baseUrl: 'https://9527.codes/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Code0',
    baseUrl: 'https://code0.ai/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'TeamoRouter',
    baseUrl: 'https://api.teamorouter.cn/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'ClaudeCN',
    baseUrl: 'https://claudecn.top/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: '火山 Agent Plan',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/plan/v3',
    model: 'ark-code-latest',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: '火山 Coding Plan',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/coding/v3',
    model: 'ark-code-latest',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'BytePlus',
    baseUrl: 'https://ark.ap-southeast.bytepluses.com/api/coding/v3',
    model: 'ark-code-latest',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Volcengine Doubao',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    model: 'doubao-seed-2-1-pro-260628',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'A6API',
    baseUrl: 'https://api.a6api.com/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Compshare',
    baseUrl: 'https://api.modelverse.cn/v1',
    model: 'gpt-6-astra',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Compshare Coding Plan',
    baseUrl: 'https://cp.compshare.cn/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'CCSub',
    baseUrl: 'https://www.ccsub.net/v1',
    model: 'gpt-6-astra',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'SSSAiCode',
    baseUrl: 'https://node-hk.sssaicodeapi.com/api/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'SoleAPI',
    baseUrl: 'https://soleapi.com/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Micu',
    baseUrl: 'https://www.micuapi.ai/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'RightCode',
    baseUrl: 'https://www.rightapi.ai/codex/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Cubence',
    baseUrl: 'https://api.cubence.com/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'CrazyRouter',
    baseUrl: 'https://cn.crazyrouter.com/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'DMXAPI',
    baseUrl: 'https://www.dmxapi.cn/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'SudoCode.chat',
    baseUrl: 'https://api.sudocode.chat/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      review_model: 'gpt-5.6-sol',
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'SudoCode.us',
    baseUrl: 'https://sudocode.us/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      review_model: 'gpt-5.6-sol',
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      model_verbosity: 'high',
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'XycAi',
    baseUrl: 'https://apicdn.xycai.us/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Tu-zi',
    baseUrl: 'https://api.tu-zi.com/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Amux',
    baseUrl: 'https://api.amux.ai/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Soshow',
    baseUrl: 'https://maas.so-show.com/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Azure OpenAI',
    baseUrl: 'https://YOUR_RESOURCE_NAME.openai.azure.com/openai',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {
        env_key: 'OPENAI_API_KEY',
        query_params: {
          'api-version': '2025-04-01-preview',
        },
      },
    },
  },
  {
    harness: 'codex',
    name: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com',
    model: 'deepseek-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Zhipu GLM',
    baseUrl: 'https://open.bigmodel.cn/api/v1',
    model: 'glm-5.3',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Zhipu GLM en',
    baseUrl: 'https://api.z.ai/api/v1',
    model: 'glm-5.3',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Baidu Qianfan',
    baseUrl: 'https://qianfan.baidubce.com/v2',
    model: 'deepseek-v4-pro',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: '千问AI平台',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    model: 'qwen3.8-max',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: '千问AI平台 Token Plan',
    baseUrl:
      'https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1',
    model: 'qwen3.8-max',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'QwenCloud',
    baseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    model: 'qwen3.8-max',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'QwenCloud Token Plan',
    baseUrl:
      'https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1',
    model: 'qwen3.8-max',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Tencent Hunyuan',
    baseUrl: 'https://tokenhub.tencentmaas.com/v1',
    model: 'hy3',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'StepFun API',
    baseUrl: 'https://api.stepfun.com/v1',
    model: 'step-3.7-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'StepFun API en',
    baseUrl: 'https://api.stepfun.ai/v1',
    model: 'step-3.7-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Longcat',
    baseUrl: 'https://api.longcat.chat/openai/v1',
    model: 'LongCat-2.0',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'MiniMax',
    baseUrl: 'https://api.minimax.cn/v1',
    model: 'MiniMax-M3',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'MiniMax en',
    baseUrl: 'https://api.minimax.io/v1',
    model: 'MiniMax-M3',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Astron Coding Plan',
    baseUrl: 'https://maas-coding-api.cn-huabei-1.xf-yun.com/v1',
    model: 'astron-code-latest',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Xiaomi MiMo',
    baseUrl: 'https://api.xiaomimimo.com/v1',
    model: 'mimo-v2.6-pro',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Xiaomi MiMo Token Plan (China)',
    baseUrl: 'https://token-plan-cn.xiaomimimo.com/v1',
    model: 'mimo-v2.6-pro',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'xAI (Grok)',
    baseUrl: 'https://api.x.ai/v1',
    model: 'grok-4.5',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'OpenCode Zen',
    baseUrl: 'https://opencode.ai/zen/v1',
    model: 'gpt-6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'AiHubMix',
    baseUrl: 'https://aihubmix.com/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'CherryIN',
    baseUrl: 'https://open.cherryin.net/v1',
    model: 'openai/gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'RelaxyCode',
    baseUrl: 'https://www.relaxycode.com/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'E-FlowCode',
    baseUrl: 'https://e-flowcode.cc/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {
        model_context_window: 1000000,
        model_auto_compact_token_limit: 9000000,
      },
    },
  },
  {
    harness: 'codex',
    name: 'PIPELLM',
    baseUrl: 'https://cc-api.pipellm.ai/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'medium',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'TheRouter',
    baseUrl: 'https://api.therouter.ai/v1',
    model: 'openai/gpt-5.3-codex',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'AICodeWith',
    baseUrl: 'https://api.aicodewith.ai/v1',
    model: 'gpt-5.6-sol',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: 'Command Code',
    baseUrl: 'https://api.commandcode.ai/provider/v1',
    model: 'deepseek/deepseek-v4.1-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'codex',
    name: '模力方舟',
    baseUrl: 'https://moark.com/v1',
    model: 'deepseek-v4-flash-0731',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      model_reasoning_effort: 'high',
      disable_response_storage: true,
      provider: {},
    },
  },
  {
    harness: 'gemini',
    name: 'Google Official',
    baseUrl: 'https://generativelanguage.googleapis.com',
    model: '',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'PackyCode',
    baseUrl: 'https://www.packyapi.ai',
    model: 'gemini-3.6-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'APINebula',
    baseUrl: 'https://apinebula.ai',
    model: 'gemini-3.6-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'AICodeMirror',
    baseUrl: 'https://api.aicodemirror.ai/api/gemini',
    model: 'gemini-3.6-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'Shengsuanyun',
    baseUrl: 'https://router.shengsuanyun.com/api',
    model: 'google/gemini-3.6-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'AIGoCode',
    baseUrl: 'https://api.aigocode.app',
    model: 'gemini-3.6-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'Qiniu',
    baseUrl: 'https://api.qnaigc.com/bypass/vertex',
    model: 'gemini-3.6-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'AICoding',
    baseUrl: 'https://api.aicoding.inc',
    model: 'gemini-3.6-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'SubRouter',
    baseUrl: 'https://subrouter.ai/v1beta',
    model: 'gemini-3.6-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: '88API',
    baseUrl: 'https://api.88api.ai',
    model: 'gemini-3.8-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'APIKEY.FUN',
    baseUrl: 'https://api.apikey.fan',
    model: 'gemini-3.6-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: '9527CODE',
    baseUrl: 'https://9527.codes',
    model: 'gemini-3.6-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'Code0',
    baseUrl: 'https://code0.ai',
    model: 'gemini-3.6-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'A6API',
    baseUrl: 'https://api.a6api.com',
    model: 'gemini-3.6-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'SSSAiCode',
    baseUrl: 'https://node-hk.sssaicodeapi.com/api',
    model: 'gemini-3.6-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'SoleAPI',
    baseUrl: 'https://soleapi.com',
    model: 'gemini-3.8-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'Cubence',
    baseUrl: 'https://api.cubence.com',
    model: 'gemini-3.6-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'CrazyRouter',
    baseUrl: 'https://cn.crazyrouter.com',
    model: 'gemini-3.6-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'SudoCode.us',
    baseUrl: 'https://sudocode.us',
    model: 'gemini-3.1-flash-lite',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'XycAi',
    baseUrl: 'https://apicdn.xycai.us',
    model: 'gemini-3.6-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'Tu-zi',
    baseUrl: 'https://api.tu-zi.com',
    model: 'gemini-3.8-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'E-FlowCode',
    baseUrl: 'https://e-flowcode.cc',
    model: 'gemini-3.6-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'CherryIN',
    baseUrl: 'https://open.cherryin.net',
    model: 'google/gemini-3.6-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api',
    model: 'gemini-3.6-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'TheRouter',
    baseUrl: 'https://api.therouter.ai',
    model: 'gemini-3.6-flash',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
  {
    harness: 'gemini',
    name: 'AICodeWith',
    baseUrl: 'https://api.aicodewith.ai/gemini_cli',
    model: 'gemini-3.1-pro-preview',
    authType: 'api_key',
    apiType: 'responses',
    settingsConfig: {
      env: {},
    },
  },
];
